### ISSUE TITLE
'IE8 - Win7' combo not supported

### ISSUE THREAD

**Issue by oncletom** [xdissent/iectrl#4]
While looking in [`ievm.coffee`](https://github.com/xdissent/iectrl/blob/master/src/ievm.coffee#L25-35), `IE8 - Win7` is listed as a valid combo.

However when I try to install it, I have this error:

``` bash
$ iectrl install "IE8 - Win7"
ERROR: no matching virtual machines found
```

Any idea?

**Comment by jasonkarns** [comment]
So there's no way to install IE8/Win7 without resorting back to ievms?

**Comment by streetlogics** [comment]
@jasonkarns - iectrl is just a wrapper around ievms, so the curl I posted above ensures your system will install ievms correctly to "open" up the option to use "IE8-Win7" with iectrl.  The problem is that the default ievms installation that iectrl uses installs IE8 by "reusing" the Windows XP image, so therefore the IE8+Win7 combo isn't available.
